# Site settings
title: Anvishi Tech 
email: anvishi@anvishi.com
description: Corporate Website of Anvishi Technology Holdings and Ventures LLC.
avatar: https://cloud.githubusercontent.com/assets/9990518/8268523/c76b2918-1756-11e5-82bd-ea7afd053502.png
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anvishi.com" # the base hostname & protocol for your site
twitter_username: anvishi
github_username:  anvishi
permalink: /:title.html
paginate: 20

# Build settings
markdown: kramdown