# Site settings
title: Anvishi Technology Holdings and Ventures LLC
email: anvishi@anvishi.com
description: > # this means to ignore newlines until "baseurl:"
  Corporate Website of Anvishi Technology Holdings and Ventures LLC.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anvishi.com" # the base hostname & protocol for your site
twitter_username: anvishi
github_username:  anvishi
permalink: /:title.html
paginate: 20

# Build settings
markdown: kramdown