# Site settings
title: Abhishek Dey Das
email: abhishek@abhis.ws
description: > # this means to ignore newlines until "baseurl:"
  Personal web site of Abhishek Dey Das.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abhis.ws" # the base hostname & protocol for your site
twitter_username: adeydas
github_username:  adeydas
permalink: /:title.html

# Build settings
markdown: kramdown
