# Site settings
title: Algorithms & Data Structures
email: abhishek@abhis.ws
description: > # this means to ignore newlines until "baseurl:"
  A collection of algorithm and data structure problems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abhis/ws/algorithms/" # the base hostname & protocol for your site
twitter_username: adeydas
github_username:  adeydas
permalink: /:title.html

# Build settings
markdown: kramdown
